server:
  port: 5431
  
s3:
  secured: true
  #OICR
  #endpoint: http://10.5.73.101
  
  #Sinai Center
  #endpoint: https://www.cancercollaboratory.org:9080
  
collaboratory:
  bucket.name: oicr.icgc.collaboratory
  upload.directory: upload
  data.directory: data
  upload.expiration: 7
  download.expiration: 7


upload:
  retry.limit: 1000
  partsize: 20000000
  
---
spring:
  profiles: amazon
  profiles.include: prod
  
s3:
  endpoint: s3-external-1.amazonaws.com
  masterEncryptionKeyId: MUST-BE-PROVIDED

---
spring:
  profiles: collaboratory
  profiles.include: prod

s3:
  endpoint: https://www.cancercollaboratory.org:9080

---
spring:
  profiles: prod
  
# Server
server:
  ssl:
    key-store-type: JKS
    key-store: src/main/cert/appliance.jks
    key-store-password: password
    key-alias: appliance

s3:
  secured: true

endpoints:
  dump.enabled: false
  env.enabled: false
  info.enabled: false

---
spring:
  profiles: benchmark

# Server
server:
  ssl:
    key-store-type: JKS

s3:
  secured: false
  #Sinai Center
  endpoint: http://www.cancercollaboratory.org:9081

---
spring:
  profiles: secure
  
# OAuth authentication server
auth:
  server:
    url: https://localhost:8443/oauth/check_token
    clientId: resource
    clientsecret: pass
      