#
# DCC Storage Server - Configuration
#

###############################################################################
# Profile - common
###############################################################################

server:
  port: 5431
  
s3:
  secured: true
  #OICR
  #endpoint: http://10.5.73.101
  
  #amazon
  endpoint: s3-external-1.amazonaws.com
  
  #Sinai Center
  #endpoint: https://www.cancercollaboratory.org:9080
  
collaboratory:
  #bucket.name: oicr.collaboratory
  bucket.name: oicr.icgc.collaboratory
  upload.directory: upload
  data.directory: data
  upload.expiration: 7
  
  # COL-131: Change pre-signed URLs TTL to 1 day max
  download.expiration: 1


upload:
  retry.limit: 5
  partsize: 20000000
  connection.timeout: 15000

---

###############################################################################
# Profile - "amazon"
###############################################################################

spring:
  profiles: amazon
  profiles.include: prod
  
s3:
  endpoint: s3-external-1.amazonaws.com
  masterEncryptionKeyId: 08f7a205-3957-42c5-aae6-6166251c7565

collaboratory:
  bucket.name: oicr.icgc.collaboratory

---

###############################################################################
# Profile - "collaboratory"
###############################################################################

spring:
  profiles: collaboratory
  profiles.include: prod

s3:
  endpoint: https://www.cancercollaboratory.org:9080

---

###############################################################################
# Profile - "prod"
###############################################################################

spring.profiles: prod
  
# Server
server:
  ssl:
    key-store-type: JKS
    key-store: src/main/cert/service.jks
    key-alias: object-store-service

s3:
  secured: true

endpoints:
  dump.enabled: false
  env.enabled: false
  info.enabled: false

# Metadata server
metadata:
  url: https://meta.icgc.org

---

###############################################################################
# Profile - "secure"
###############################################################################

spring.profiles: secure
  
# OAuth authentication server
auth:
  server:
    url: https://localhost:8443/oauth/check_token
    clientId: resource
    clientSecret: pass
    uploadScope: s3.upload
    downloadScope: s3.download
    #uploadScope: os.upload
    #downloadScope: os.download

---

###############################################################################
# Profile - "dev"
###############################################################################

spring.profiles: dev

s3:
  secured: false
  endpoint: localhost:9444/s3
  accessKey: AKIAIOSFODNN7EXAMPLE 
  secretKey: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY

# Server
server:

collaboratory:
  bucket.name: test.icgc

---

###############################################################################
# Profile - "benchmark"
###############################################################################

spring.profiles: benchmark

# Server
server:
  ssl:
    key-store-type: JKS

s3:
  secured: false
  #Sinai Center
  endpoint: http://www.cancercollaboratory.org:9081