#
# DCC Storage Server - Configuration
#

###############################################################################
# Profile - common
###############################################################################

server:
  port: 5431
  
s3:
  secured: true
  
  #amazon
  endpoint: s3-external-1.amazonaws.com
  
collaboratory:
  bucket.name: oicr.icgc
  state.bucket.name: oicr.icgc
  upload.directory: upload
  upload.expiration: 7
  data.directory: data
  
  # COL-131: Change pre-signed URLs TTL to 1 day max
  download.expiration: 1

upload:
  retry.limit: 5
  partsize: 20000000
  connection.timeout: 15000
  
  # Every day at midnight
  clean.cron: "0 0 0 * * ?" 
  clean.enabled: true

---

###############################################################################
# Profile - "ssl"
###############################################################################

spring.profiles: ssl
  
# Server
server:
  ssl:
    key-store-type: JKS
    key-store: src/main/cert/service.jks
    key-alias: object-store-service

---

###############################################################################
# Profile - "amazon"
###############################################################################

spring:
  profiles: amazon
  profiles.include: prod
  
s3:
  endpoint: s3-external-1.amazonaws.com
  masterEncryptionKeyId: af628f04-ac12-4b11-bf83-6545fd44ad18

collaboratory:
  bucket.name: oicr.icgc

---

###############################################################################
# Profile - "collaboratory"
###############################################################################

spring:
  profiles: collaboratory
  profiles.include: prod

s3:
  endpoint: https://www.cancercollaboratory.org:9080
  masterEncryptionKeyId: 

---

###############################################################################
# Profile - "prod"
###############################################################################

spring.profiles: prod

s3:
  secured: true

endpoints:
  dump.enabled: false
  env.enabled: false
  info.enabled: false

# Metadata server
metadata:
  url: https://meta.icgc.org

---

###############################################################################
# Profile - "secure"
###############################################################################

spring.profiles: secure
  
# OAuth authentication server
auth:
  server:
    url: https://localhost:8443/oauth/check_token
    clientId: resource
    clientSecret: pass
    uploadScope: s3.upload
    downloadScope: s3.download
    #uploadScope=collab.upload
    #downloadScope=collab.download

---

###############################################################################
# Profile - "dev"
###############################################################################

spring.profiles: dev

s3:
  secured: false
  endpoint: localhost:9444/s3
  accessKey: AKIAIOSFODNN7EXAMPLE 
  secretKey: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY

# Server
server:

collaboratory:
  bucket.name: test.icgc
  
upload:
  clean.enabled: false

---

###############################################################################
# Profile - "benchmark"
###############################################################################

spring.profiles: benchmark

# Server
server:
  ssl:
    key-store-type: JKS

s3:
  secured: false
  # Sinai Center
  endpoint: http://www.cancercollaboratory.org:9081