spring:
  profiles.active: default
---
spring:
  profiles: default

# Server
server:
  port: 5431
  ssl:
    key-store: src/main/cert/appliance.jks
    key-store-type: JKS
    key-store-password: password
    key-alias: appliance
  
s3:
  secured: true
  #OICR
  #endpoint: http://10.5.73.101
  #accessKey: c6525e9b10804c1c9306d7051b10a3b3
  #secretKey: 36c1aec6a9014fee95b0459d43d6bc6e
  
  #Sinai Center
  #endpoint: https://www.cancercollaboratory.org:9080
  #accessKey: 29c65c06a9de4e35b8baa4a0fc12193e
  #secretKey: 536d4ff664cc4509a7fce5b9a604e1aa

  endpoint:

collaboratory:
  bucket.name: oicr.collaboratory
  upload.directory: upload
  data.directory: data
  upload.expiration: 14


upload:
  retry.limit: 1000
  partsize: 20000000
---
spring:
  profiles: prod
  
s3:
  secured: true
  #Sinai Center
  endpoint: https://www.cancercollaboratory.org:9080
  accessKey: 29c65c06a9de4e35b8baa4a0fc12193e
  secretKey: 536d4ff664cc4509a7fce5b9a604e1aa

endpoints:
  dump.enabled: false
  env.enabled: false
  info.enabled: false
