#
# Object Store Client - Configuration
#

###############################################################################
# Profile - common
###############################################################################

transport:
  fileFrom: memory
  memory: 1
  parallel: 6

client:
  ansi: ${ansi:true}
  silent: ${silent:false}
  accessToken: "${accessToken}" #Alias for backwards compatibility

  upload:
    serviceHostname: localhost
    servicePort: 5431
    retryNumber: 10
    retryTimeout: 1
    
  ssl:
    enabled: false
    custom: false

# Metadata server
metadata:
  url: https://meta.icgc.org/entities
  ssl:
    enabled: true
    
logging:
  file: target/logs/client.log

---

###############################################################################
# Profile - "amazon"
###############################################################################

spring.profiles: amazon

client:
  upload:
    serviceHostname: objectstore.cancercollaboratory.org

  # SSL
  ssl:
    enabled: true
    custom: true
    
    trustStore: classpath:client.jks
    trustStoreType: JKS
    trustStorePassword: CLIENT_SECRET
    trustName: icgc.cancercollaboratory.org

---

###############################################################################
# Profile - "oicr"
###############################################################################

spring.profiles: oicr

client:
  upload:
    serviceHostname: objectstore.icgc.org
    servicePort: 443
    
  ssl:
    enabled: true
    custom: false

---

###############################################################################
# Profile - "debug"
###############################################################################

spring.profiles: debug

logging:
  level:
    org.icgc.dcc.storage: DEBUG
    springframework.retry: DEBUG
    springframework.web: DEBUG
    com.amazonaws.services: DEBUG
