#
# Storage Client - Configuration
#

###############################################################################
# Profile - common
###############################################################################

client:
  ansi: ${ansi:true}
  silent: ${silent:false}
  quiet: ${quiet:false}
  accessToken: "${accessToken}" # Alias for backwards compatibility
    
  ssl:
    custom: false

transport:
  fileFrom: memory
  memory: 1
  parallel: 6

storage:
  url: http://localhost:5431
  retryNumber: 10
  retryTimeout: 1	

metadata:
  url: https://meta.icgc.org
  ssl:
    enabled: true
    
portal:
  url: https://dcc.icgc.org  
    
logging:
  file: target/logs/client.log
  
mount:
  logging: false

---

###############################################################################
# Profile - "amazon"
###############################################################################

spring.profiles: amazon

storage:
  url: https://virginia.cloud.icgc.org

client:
  ssl:
    custom: false
    
---

###############################################################################
# Profile - "collab"
###############################################################################

spring.profiles: collab

# Storage server
storage:
  url: https://storage.cancercollaboratory.org:5431

client:    
  ssl:
    custom: true
    
    trustStore: classpath:client.jks
    trustStoreType: JKS
    trustStorePassword: CLIENT_SECRET
    trustName: icgc.cancercollaboratory.org    

---

###############################################################################
# Profile - "oicr"
###############################################################################

spring.profiles: oicr

storage:
  url: https://objectstore.icgc.org

client:    
  ssl:
    custom: false

---

###############################################################################
# Profile - "debug"
###############################################################################

spring.profiles: debug

logging:
  level:
    org.icgc.dcc.storage: DEBUG
    springframework.retry: DEBUG
    springframework.web: DEBUG
    com.amazonaws.services: DEBUG
