#
# Storage Client - Configuration
#

###############################################################################
# Profile - common
###############################################################################

transport:
  fileFrom: memory
  memory: 1
  parallel: 6

client:
  ansi: ${ansi:true}
  silent: ${silent:false}
  quiet: ${quiet:false}
  accessToken: "${accessToken}" #Alias for backwards compatibility
  connectTimeoutSeconds: 60
  readTimeoutSeconds: 60

  upload:
    serviceHostname: localhost
    servicePort: 443
    retryNumber: 10
    retryTimeout: 1
    
  ssl:
    enabled: false
    custom: false

# Metadata server
metadata:
  url: https://meta.icgc.org
  ssl:
    enabled: true
    
portal:
  url: https://dcc.icgc.org  
    
logging:
  file: target/logs/client.log
  
mount:
  logging: false

---

###############################################################################
# Profile - "amazon"
###############################################################################

spring.profiles: amazon

client:
  upload:
    serviceHostname: virginia.cloud.icgc.org

  # SSL
  ssl:
    enabled: true
    custom: false
    
---

###############################################################################
# Profile - "collab"
###############################################################################

spring.profiles: collab

client:
  upload:
    serviceHostname: storage.cancercollaboratory.org
    servicePort: 5431
    
  # SSL
  ssl:
    enabled: true
    custom: true
    
    trustStore: classpath:client.jks
    trustStoreType: JKS
    trustStorePassword: CLIENT_SECRET
    trustName: icgc.cancercollaboratory.org    

---

###############################################################################
# Profile - "oicr"
###############################################################################

spring.profiles: oicr

client:
  upload:
    serviceHostname: objectstore.icgc.org
    servicePort: 443
    
  ssl:
    enabled: true
    custom: false

---

###############################################################################
# Profile - "debug"
###############################################################################

spring.profiles: debug

logging:
  level:
    org.icgc.dcc.storage: DEBUG
    springframework.retry: DEBUG
    springframework.web: DEBUG
    com.amazonaws.services: DEBUG
