repository_server_uri: https://hrepo1-dcc.oicr.on.ca:9443
#repository_server_uri: https://10.5.74.100:8443
#server:
#  ssl:
    #Enable this if we need client certificate and develop TrustManager to add the local trust store
    #client-auth: need 
    #trust-store: /Users/JLam/git/dcc-repository/dcc-repository-client/src/main/resources/key/strict/appliance.jks 
    #trust-store-type: JKS
    #trust-store-password: password
    #key-store: src/main/cert/keystore.p12
    #key-store-type: PKCS12
    #key-store-password: P@ssw0rd  
