#
# Collaboratory Client - Configuration
#
client.directory: ${user.home}

transport:
  fileFrom: memory
  memory: 1
  parallel: 6

client:
  strictSsl: false
  home: ${client.directory}

  upload:
    serviceHostname: localhost
    servicePort: 5431
    retryNumber: 10
    retryTimeout: 1
    
logging:
  file: target/logs/client.log

---
spring:
  profiles: prod

client:
  strictSsl: true

  # SSL
  ssl:
    trustStore: classpath:client.jks
    trustStoreType: JKS
    trustStorePassword: password
    trustName: repository.icgc.org

---
spring:
  profiles: debug

logging:
  level:
    collaboratory: DEBUG
    springframework.retry: DEBUG
    springframework.web: DEBUG
    com.amazonaws.services: DEBUG
---
spring:
  profiles: secure
  
accessToken: "CHANGE_ME"