#
# Collaboratory Client - Configuration
#
logging.level.collaboratory: DEBUG
client.directory: ${user.home}

spring:
  profiles.active: default
---
spring:
  profiles: default

transport:
  fileFrom: memory
  memory: 1
  parallel: 2

client:
  strictSsl: true
  home: ${client.directory}

  upload:
    serviceHostname: localhost
    servicePort: 5431
    retryNumber: 100
    retryTimeout: 1
   
  # SSL
  ssl:
    trustStore: classpath:client.jks
    trustStoreType: JKS
    trustStorePassword: password
    trustName: repository.icgc.org
    #keyStore: file:///${client.directory}/cert/client.jks
    #keyStoreType: JKS
    #keyStorePassword: password
    #keyAlias: client
    
logging:
  file: target/logs/client.log
---
spring:
  profiles: override