#
# Collaboratory Client - Configuration
#

###############################################################################
# Profile - common
###############################################################################

client.directory: ${user.home}

transport:
  fileFrom: memory
  memory: 1
  parallel: 6

client:
  strictSsl: false
  home: ${client.directory}

  upload:
    serviceHostname: localhost
    servicePort: 5431
    retryNumber: 10
    retryTimeout: 1

    
logging:
  file: target/logs/client.log

---

###############################################################################
# Profile - "prod"
###############################################################################

spring.profiles: prod

client:
  strictSsl: true

  upload:
    serviceHostname: objectstore.cancercollaboratory.org

  # SSL
  ssl:
    trustStore: classpath:client.jks
    trustStoreType: JKS
    trustStorePassword: CLIENT_SECRET
    trustName: icgc.cancercollaboratory.org

---

###############################################################################
# Profile - "oicr"
###############################################################################

spring.profiles: oicr

client:
  strictSsl: true

  upload:
    serviceHostname: storage.icgc.org

---

###############################################################################
# Profile - "secure"
###############################################################################

spring.profiles: secure

# OAuth2 authorization token
accessToken: "CHANGE_ME"

---

###############################################################################
# Profile - "debug"
###############################################################################

spring.profiles: debug

logging:
  level:
    collaboratory: DEBUG
    springframework.retry: DEBUG
    springframework.web: DEBUG
    com.amazonaws.services: DEBUG
