#
# Collaboratory Client - Configuration
#
client.directory: ${user.home}

spring:
  profiles.active: default

---
spring:
  profiles: default

transport:
  fileFrom: memory
  memory: 1
  parallel: 2

client:
  strictSsl: true
  home: ${client.directory}

  upload:
    serviceHostname: localhost
    servicePort: 5431
    retryNumber: 100
    retryTimeout: 1
   
  # SSL
  ssl:
    trustStore: classpath:client.jks
    trustStoreType: JKS
    trustStorePassword: password
    trustName: repository.icgc.org
    
logging:
  file: target/logs/client.log

---
spring:
  profiles: prod

client:
  strictSsl: true

---
spring:
  profiles: debug
  profiles.include: prod

logging:
  level:
    collaboratory: DEBUG
    springframework.retry: DEBUG
    springframework.web: DEBUG
    com.amazonaws.services: DEBUG
---
spring:
  profiles: secure
  
accessToken: "CHANGE_ME"